### ISSUE TITLE
Problem with mex while building sharktools under Mac

### ISSUE THREAD

**Issue by brainprince** [armenb/sharktools#7]
Hi there
I would like to use sharktools under Mac Os x 10.8 with matlab. 
The configure command runs through with out any error, but while executing the make command I get following error:

--- making matshark ---
/Applications/MATLAB_R2011a.app/bin/mex -maci64   -cxx -o matshark matshark.c -L. -L/sw/lib -lgmodule-2.0 -lglib-2.0 -lintl -Wl,-rpath /Applications/Wireshark.app/Contents/Resources/lib -L/Applications/Wireshark.app/Contents/Resources/lib -lwireshark -lwiretap -lwsutil -lsharktools -I. -I/Users/<me>/src/wireshark-1.8.6 -I/Users/<me>/src/wireshark-1.8.6/wiretap -I/sw/include/glib-2.0 -I/sw/lib/glib-2.0/include
In file included from /Users/<me>/src/wireshark-1.8.6/epan/exceptions.h:29,
                 from /Users/<me>/src/wireshark-1.8.6/epan/tvbuff.h:41,
                 from /Users/<me>/src/wireshark-1.8.6/epan/ftypes/ftypes.h:149,
                from sharktools_core.h:52,
                 from matshark.c:47:
/Users/<me>/src/wireshark-1.8.6/epan/except.h:96: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'void'
/Users/<me>/src/wireshark-1.8.6/epan/except.h:97: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'void'
/Users/<me>/src/wireshark-1.8.6/epan/except.h:98: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'void'
/Users/<me>/src/wireshark-1.8.6/epan/except.h:99: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'void'
In file included from matshark.c:47:
sharktools_core.h:99: error: expected specifier-qualifier-list before 'capture_file'
matshark.c: In function 'mexFunction':
matshark.c:446: warning: assignment from incompatible pointer type

```
mex: compile of ' "matshark.c"' failed.
```

make[1]: **\* [matshark] Error 1
make: **\* [all-recursive] Error 1

I am not sure what I missed or what I could have done wrong.
Any ideas ?
Thanks for your help.
Best
-M

**Comment by sinkyh** [comment]
I am having a similar issue but with OS X 10.9. Were you able to resolve it?

**Comment by imre-szekeres** [comment]
Hi!

I'm havin' a similar case under ubuntu 14.04, after attemptin' sudo make I get this error message.
Has anyone resolved this issue?

Best wishes,
Imre!

**Comment by armenb** [comment]
Unfortunately, I have not had access to mex lately, so it's almost impossible for me to fix this issue.

I'd suggest using pyshark instead, but there is also the issue that I haven't tried getting pyshark to work on post-Wireshark-1.8.0 systems due to lack of need on my part.  I'll try giving it a shot soon, though.

**Comment by imre-szekeres** [comment]
Thank you very much for your answer, Ive workd it out. Found a workaround for what I would have used sharktools for.

**Comment by loneharoon** [comment]
Hello All,
Can anyone of you help me in sorting this issue. I am facing the same problem.
